-- Demo seed was moved to local-only Flyway migrations.
--
-- Default/prod runs only normal schema/catalog migrations from:
--   classpath:db/migration
--
-- Local demo data is applied only when the Spring `local` profile is active:
--   classpath:db/migration,classpath:db/local-migration
--
-- Run locally with:
--   .\gradlew.bat bootRun --args='--spring.profiles.active=local'
--
-- The seed is intentionally split by responsibility:
--   V1000__reset_demo_runtime_users.sql
--   V1001__seed_demo_users_and_doctors.sql
--   V1002__seed_demo_patients.sql
--   V1003__seed_demo_examinations.sql
--   V1004__seed_demo_examination_measurements.sql
--
-- This file intentionally contains no data mutations.
